### ISSUE TITLE
Отказаться от использования np.where

### ISSUE THREAD

**Issue by a-bagrov** [egor-ciu/sand-production#1]
Егор, приветствую,

Просьба в следующих версиях скрипта отказаться от использования np.where в пользу next, т.к. np.where почему-то у нас не заработал.
Например: вместо
`np.where(t_array <= t[0])[0][-1]` просьба использовать `next(t_k for t_k in t_array if t_k <= t[0])`
Спасибо!

**Comment by egor-ciu** [comment]
Ок, только сейчас увидел. Добавлю в следующей итерации.

**Comment by egor-ciu** [comment]
Сделал!

**Comment by a-bagrov** [comment]
Спасибо!
